name: Update Calendar

on:
  schedule:
    # Ejecuta todos los días a las 5 AM UTC.
    - cron:  '0 5 * * *'
  push:
    branches:
      - main
  workflow_dispatch: {}# Esto permite la ejecución manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run script
      run: python menu_only.py

    - name: Commit and push if changed
      run: |
        git config --global user.name 'Daniel Martínez'
        git config --global user.email 'wakkos@gmail.com'
        git add -A
        git diff --quiet && git diff --staged --quiet || git commit -m "Update calendar"
        git push