name: Update Calendar

on:
  schedule:
    # Ejecuta todos los días a las 5 AM UTC.
    - cron:  '0 5 * * *'
  push:
    branches:
      - feature/test-deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      run: python script.py

    - name: Commit and push if changed
      run: |
        git config --global user.name 'Your Name'
        git config --global user.email 'your-email@example.com'
        git add -A
        git diff --quiet && git diff --staged --quiet || git commit -m "Update calendar"
        git push
